# Generated by Django 4.1.1 on 2022-09-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                decimal_places=2,
                error_messages={
                    "name": {"max_length": "The Price Must Be Between 0 to 9999.99"}
                },
                help_text="Maximum 9999.99",
                max_digits=5,
                verbose_name="Discount Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="regular_price",
            field=models.DecimalField(
                decimal_places=2,
                error_messages={
                    "name": {"max_length": "The Price Must Be Between 0 to 9999.99"}
                },
                help_text="Maximum 9999.99",
                max_digits=5,
                verbose_name="Regular Price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
